# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/919106840315/919106840315.srcs/sources_1/bd/ps919106840315/ip/ps919106840315_processing_system7_0_0/ps919106840315_processing_system7_0_0.xci
# IP: The module: 'ps919106840315_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/919106840315/919106840315.srcs/sources_1/bd/ps919106840315/ip/ps919106840315_processing_system7_0_0/ps919106840315_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps919106840315_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: e:/919106840315/919106840315.srcs/sources_1/bd/ps919106840315/ip/ps919106840315_processing_system7_0_0/ps919106840315_processing_system7_0_0.xci
# IP: The module: 'ps919106840315_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/919106840315/919106840315.srcs/sources_1/bd/ps919106840315/ip/ps919106840315_processing_system7_0_0/ps919106840315_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ps919106840315_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
