# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/item3.xdc

# Block Designs: bd/ps919106840315/ps919106840315.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps919106840315 || ORIG_REF_NAME==ps919106840315} -quiet] -quiet

# IP: bd/ps919106840315/ip/ps919106840315_processing_system7_0_0/ps919106840315_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ps919106840315_processing_system7_0_0 || ORIG_REF_NAME==ps919106840315_processing_system7_0_0} -quiet] -quiet

# XDC: bd/ps919106840315/ps919106840315_ooc.xdc
